apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wxqvx1glg-python
  janus-idp.io/tekton: wxqvx1glg-python
  backstage.io/kubernetes-id: wxqvx1glg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wxqvx1glg-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
